### ISSUE TITLE
Apply IE's 12 heuristics for the project

### ISSUE THREAD

**Issue by julianharty** [julianharty/web-accessibility-testing#16]
### Context
Software tools can often frustrate and/or disappoint the people who would use them. There's an opportunity to actively consider the intended use of software tools in order to improve the utility and user experience of particular software tools. 

Active research in this area has led to 12 heuristics that are intended to provide a guide and/or a measures. The current release of the heuristics is available at https://github.com/hci-lab-um/heuristics-for-test-tool-design/blob/main/README.md

### The 12 heuristics

Summary list of heuristic questions
Theme: WHY?

   1. Why do we need this tool?

Theme: WHO?

   2. Who will use or be affected by the tool?
   3. What previous experiences do people bring to the tool?
   4. What communication needs or preferences do those people have?
   5. What learning perspectives or goals do those people bring?
   6. What learning preferences do those people have?

Theme: CONTEXT?

   7. Where will the tool be used?
   8. What workflows will the tool be part of?
   9. What risks are associated with those workflows?
   10. What work styles are acceptable in those workflows and teams?
   11. When will the tool be used?
   12. How long will the tool be used?

### Tasks
Ask each of these 12 questions for this project and write down:

- [ ] Initial thoughts/answers
- [ ] observations on the utility of these heuristics
- [ ] any additions/amendments/etc. that may improve the set of heuristics.
